script: bash ./deploy.sh
language: node_js
node_js:
- 5.10.1
branches:
  only:
  - master
env:
  global:
  - GH_REF: github.com/jarrrgh/palju-demo.git
  - secure: "OD5jdG4a+MuU/ycaFuA09AOv/yTqLi8hIF0HLSKAVI9QeTSYux1ixXpx2C7BZYDTyGYbBkTEmnOg2T6cmuvWW26WqEoKv4PUhx0ExYpIf1KGrAiCXcwGlnwup5VsdARFAgW4korlXNvH2cVV/yEhBbAg7Hv9qJDmTLXses04ELqonmhb4qeQMgdswJvpidZaFLTtd5Bjwd9UtQeOS06z2y2rjdZyk7pBpYuicaPG9bmRyUCnPV7+7lZy1V5A7KQK3n+cxnAWOMnDqMTl/zaK+uu3l1CbQEwsnQTVfVHgKKjsTjkuP9HCZIsp2b9GsaESHuIACXIHe7RuSw9syLwlTuyelAAL7M5sLwGRTM7DGSdUaH9hpl9k2QbghMlKdCO2OkTWWEwHF+MasqFyAjbM114mcR+vvwaqLkyEN9rFB8p6kH1IwT/sH6h7ssBmsniLFzj+JRDlgRYkodxB5nBAbFbMMw/gl4+lCjrNlOuM266HepEVuHL4WyJrmfUjU+0fsgShGU2zaebxt3TSMsNSCzhrHWLj1ka/u/mSDWw12bl3DqeeBvA4XBZAkdkDx3X4XdfF8lkqy+3NQcYjOB8SG13MY3phYdrDBREr7+G9hJugJDnpYqlSmPqSNWmcB+7XYZT779843Na+KYGioXBXB6fVakFCadjDas1bZekrfFQ="
