script: bash ./deploy.sh
language: node_js
node_js:
- 5.10.1
branches:
  only:
  - master
env:
  global:
  - GH_REF: github.com/jarrrgh/palju-demo.git
  - secure: Beu7RoX3vgC4wMBiX4O0umcSxtUgBl8JfFF6CVfkTOV3A3nSSy9yv+BUu8R0Nwy+Wf6o6g0Cw061qMEE+GNL3mrgtlT4yucJZX396eQKDHFHtjzhQ3AYVwYJlXSQntuFVQp3haqhhL8C/sNz05EhOoPJeS+YYHHB/GGBGFnPv7cxAkmPzMo5i7JUTfIcJug94Td6RWHslJtIH6eCeaALLqCn559p5BRjZrktGPz8VIXQhF7RIODhIWYhGnolRbAOxN0QV1KFHw6q5cU4pCzdGqMJG39PiLkIM1DbdUd5lbxbkyc03n6Jt7xaszY13V9OC5RXi6ANpY3wIfg4eKyIXFs2HATFM6HNuqcFP3t9tAzNhxRycfccXo4lepLbl1QZyr+7VqFn1hLgcelXuU7QTHqK5koPZY27DHFFk8tpn2RNUTvgCOHM8QMEeBR0h3ZxWDKJLz6090RbJiQoY+hn9xzD3Gj4h8utjGNvxi6FYKHfvDXBj8QyRyEkREN+7LoBMEdHjMP7y5HU8JHjzyRky0GfKfDAYPDCErioqDOgZ32vuGULiVq5Slv9gMzv2omwwm87eB+ymqO9gZxT4ef1OpjmFnN9mMFuYPhRud7MeKl/Iin8jqiSjUgJxhvepKObf9wF9kBvZZkdn4Y6zjhgHepRSAUF424txGKYZMgz9qc=
