script: bash ./deploy.sh
language: node_js
node_js:
- 5.10.1
branches:
  only:
  - master
env:
  global:
  - GH_REF: github.com/jarrrgh/palju-demo.git
  - secure: "MxfOClBZfu/rkYl8hLKUzz36RfDAIyIfUiJ/tuOnoq9M3m8zMS6gHbqSYPLVX6ft5cEKjXitunIofp9x6Z1wr8KJHwCvvFtCBBEJ9OvxdF81ab161PH3BixAUVBcbUZuGEvaW2VyclO6nVrcuuVgYHkeDy5BP7972g/WOdWsYus2zWQZHk5+VO2Jq+RT0IoV+wNw0IevUEQWauiU84S83HjBLKNAGmq2ybEVSl4SffX2LbfPcgvIEzDYYL2i1MKMZYwpxuLFrjFx57M8+TQd61fu2e8AP1616yzjD1VfH47a91jc7JiJE+/eHH7/0Da0INpoLyz2MfDG+mY2ghhtREp+mh0Qoo7AgehmD5DAiZgQ2cxOdrODbG4GLWEdlxrFoWH7GPLxE0UyhVrGPkdA20aMd+XfA0tjgUuQC3HWX3ySth+9raPXSQz11o9Rbz2pyh7r9J71XrCEdh682r3b20K0MVrVMtmgcEO42NZEHKZmxokgVGk70/WLHj8inqfT0h4XPa9axjWNvAVwpOsTm2sF0m2lyGM0YdZVm4IxdQBBuFvu0XZpxRNPx2z5yGft2Dos9K/NXGsim2EPYa3o2xdhnjnnWzuJi+NfmG2SyMBesR0iTjGbnVSP865kktfKsMrpLVNYzY+Tx1PZ5oXP0jBDLceBNFjQkkeY1bE4LH4="
