script: bash ./deploy.sh
language: node_js
node_js:
- 5.10.1
branches:
  only:
  - master
env:
  global:
  - GH_REF: github.com/jarrrgh/palju-demo.git
  - secure: "ePUIVkJgrKMhFR3hfytybsEbKFqI+PiSQ2eyjXfl4Ko/UlJ9Qe8czp6qZws4P0c3Rz8d7Y/J6rJHd8y3Hgm2LbL5vp7LMS+udPYzKom8ZHTTuFWp5d7LOZx2I600HSD4bs6ucHBXagRfVg43vyNsAomEyyNHa0UQWbQ3gDv7puX0LIL7joNl29+NnGbxKvdoARhzo3YGOHsoeovHPX43aPW67TuIe9Dwlsgl9LsASgVfLxizySgW+ku0ts7K0RiEy3g7UEs6zKxCrjI+eYYABsQUoXXpMTRX4OjxqvbK20J+FlRgyDMvXljFEOVocZYzYVsOUCGYQWDmCEfJZ7qtw7CJk/3f2UZcHkK8PimSz0gWPH+xypgZvo85WnFEgXcFSxZemTd1LvjcU7q/8aJUbnSe5tl3KuL1Jv/2MALaY+k5yxS7bZqF1jVw65K+ZYEJY2BxFSjTl3YlMa9M0Co0k0uaNmREgued2d6kxn+YAq6H9nBwP6Qo4ieKjwdJoK317FVXoMKTzHn64gFx8T9gAxqvzBChKPPCRkC/dxyLUzu1ASsapj6sbEKVKEtJe57pOH+4W5vng3IbemtGt+Fc+aoVUkWdlKQrXZhX0HIdxmBqbLsqyb7s4O7CbdD45I+hZvhZyedxTLmSAiK/PhHC/pubjbE++o4mtzBcuVzrFrs="
